[package]
name = "operator"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
futures-util = { workspace = true }

shared = { path = "../shared" }
pools = { path = "../pools" }
