//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "contract_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tx_hash: String,
    pub log_index: i64,
    pub emit_at: DateTimeWithTimeZone,
    pub chain_id: i64,
    pub contract_address: String,
    pub signature: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub args: Json,
    pub is_stream_missing: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
