//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::enums::TxnStatus;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "distribute_user_fund_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tx_hash: String,
    pub log_index: i64,
    pub emit_at: DateTimeWithTimeZone,
    pub chain_id: i64,
    pub strategy_address: String,
    pub depositor: String,
    pub deposited_token_address: String,
    pub underlying_asset: String,
    pub swap_contract: String,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub amount: Decimal,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub actual_amount_out: Decimal,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub strategy_share: Decimal,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub distributed_fee: Decimal,
    pub rebalance_status: TxnStatus,
    pub attempt_retry: i32,
    pub smf_error_msg: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
