//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "transfer_fund_cross_chain_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tx_hash: String,
    pub log_index: i64,
    pub emit_at: DateTimeWithTimeZone,
    pub chain_id: i64,
    pub depositor: String,
    pub deposited_roken: String,
    pub token_in_for_bridge: String,
    pub token_out_for_bridge: String,
    pub cross_chain_dex_sender: String,
    pub cross_chain_dex_receiver: String,
    pub strategy_destination: String,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub actual_amount_bridge_cross_chain: Decimal,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub distribution_fee: Decimal,
    pub transport_msg: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
