//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "withdraw_fund_same_chain_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tx_hash: String,
    pub log_index: i64,
    pub emit_at: DateTimeWithTimeZone,
    pub chain_id: i64,
    pub receiver: String,
    pub user: String,
    pub strategy_address: String,
    pub token_address: String,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub share: Decimal,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub actual_withdraw_amount: Decimal,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
