//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::enums::TxnStatus;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "withdraw_fund_cross_chain_from_operator_event")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub tx_hash: String,
    pub log_index: i64,
    pub emit_at: DateTimeWithTimeZone,
    pub chain_id: i64,
    pub receiver: String,
    pub token_out: String,
    pub transport_msg: String,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub total_amount_out: Decimal,
    #[sea_orm(column_type = "Decimal(Some((90, 0)))")]
    pub withdraw_fee: Decimal,
    pub distribute_status: TxnStatus,
    pub attempt_retry: i32,
    pub smf_error_msg: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
