[package]
name = "events-subscriber"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }

shared = { path = "../shared" }
