openapi: 3.1.0
info:
    title: Moneyfi api documentation
    version: "1.0"
    description: moneyfi
    contact:
        email: be@moneyfi.fund
        name: BeMoneyfi
        url: https://github.com/BeMoneyfi

servers:
    - url: https://api.server.test/v1
      description: dev
    - url: http://localhost:8080
      description: local

components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
            description: auth token
    schemas:
        Tokens:
            type: object
            properties:
                access_token:
                    type: string
                renew_token:
                    type: string
            required:
                - access_token
                - renew_token

paths:
    /auth/message:
        get:
            tags:
                - auth
            description: Get auth message for signing
            parameters:
                - in: query
                  name: address
                  description: Wallet address
                  required: true
                  schema:
                      type: string
                      example: GP2r8coxtqfWFFznuNVg7SkXkPQWFyXYVPgK3yEgknH3

            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    msg:
                                        type: string
                                required:
                                    - msg
                    description: OK

    /auth/sign-in:
        post:
            tags:
                - auth
            description: Sign in
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                signature:
                                    type: string
                                address:
                                    type: string
                                ref_by:
                                    type: string
                            required:
                                - signature
                                - address
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Tokens"
                    description: OK

    /auth/renew-tokens:
        post:
            tags:
                - auth
            description: Renew tokens
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                renew_token:
                                    type: string
                            required:
                                - renew_token
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Tokens"
                    description: OK

    /users/me:
        get:
            description: Get user info
            tags:
                - users
            security:
                - BearerAuth: []
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: number
                                    address:
                                        type: string
                                required:
                                    - id
                                    - address
                    description: OK
